name = "adeptapp"
compatibility_date = "2024-01-14"
compatibility_flags = ["nodejs_compat"]

[pages_build_config]
build_command = "npx @cloudflare/next-on-pages@1"
pages_build_output_dir = ".vercel/output/static"
