name = "adeptapp"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-01-14"
compatibility_flags = ["nodejs_compat"]

[vars]
SKIP_DEPENDENCY_INSTALL = "true"
NODE_VERSION = "22.16.0"
